oldw <- getOption("warn")
options(warn = -1)


suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(ggplot2))

option_list <- list( 
  make_option(c("-R", "--results"), action="store",
              help="HYENA results file with the significant genes '_sig.txt'"),
  make_option(c("--type"), action="store_true", default=FALSE,
              help="Group samples by cancer type [default %default]"),
  make_option(c("-d", "--dir"), action="store", default= "./intermediate/run_PC0/matrix/", 
              help="Folder for gene expression matrices generated by HYENA.R [default %default]"),
  make_option(c("-w", "--write"), action="store", default="./results/plots/",
              help="Output folder [default %default]")
)

parser <- OptionParser(usage="%prog [options]", option_list=option_list, description="")
args <- parse_args(parser, positional_arguments=0)
opt <- args$options


if (!(file.exists(opt$write))) {
  dir.create(opt$write, recursive = TRUE)
}

results <- fread(opt$results, stringsAsFactors = FALSE)
genes <- results$gene_id

gene_id <- c()
FC <- c()

for (i in genes) {
  mat_file <- paste0(opt$dir, i, "_mat.txt")
  mat <- fread(mat_file, stringsAsFactors = FALSE)

  if(opt$type){
    # grouped by cancer type  
      p1 <- ggplot(mat, aes(x = cancer_type, y = fpkm.qn)) +
      geom_boxplot(
        aes(fill = sv_status), width = 0.7, size = 0.3,
        position = position_dodge(0.8), outlier.shape = NA,
      ) +
      geom_jitter(
        aes(fill = sv_status,color = sv_status), 
        position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8),
        color = "black",
        size = 0.6
      ) + 
      scale_fill_manual(values = c("#999999", "#E69F00")) +
      scale_y_continuous(limits = c(0, NA)) +
      theme_classic() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
      labs(title = i,
           subtitle = "Gene expression",
           x = "cancer type",
           y = "FPKM-QN",
           colour = "sv status")

      # grouped by cancer type (normal score)
      p2 <- ggplot(mat, aes(x = cancer_type, y = fpkm.qn.ns)) +
      geom_boxplot(
        aes(fill = sv_status), width = 0.7, size = 0.3,
        position = position_dodge(0.8), outlier.shape = NA,
      ) +
      geom_jitter(
        aes(fill = sv_status,color = sv_status), 
        position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8),
        color = "black",
        size = 0.6
      ) + 
      scale_fill_manual(values = c("#999999", "#E69F00")) +
      theme_classic() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
      labs(title = i,
           subtitle = "Gene expression",
           x = "cancer type",
           y = "FPKM-QN-NS",
           colour = "sv status")

      pdf(paste0(opt$write, i,"_fpkm.qn.grouped.pdf"), width = 12, height = 6)
      print(p1)
      dev.off()

      pdf(paste0(opt$write, i,"_fpkm.qn.ns.grouped.pdf"), width = 12, height = 6)
      print(p2)
      dev.off()

      
      if (median(mat[mat$sv_status == "no_sv"][,fpkm.qn]) == 0)
      {
      	FC <- c(FC, "Inf")
      }
      else
      {
      	FC <- c(FC, median(mat[mat$sv_status == "sv"][,fpkm.qn]) / median(mat[mat$sv_status == "no_sv"][,fpkm.qn]))
      }
  
  } else {
      p1 <- ggplot(mat, aes(x=sv_status, y=fpkm.qn.ns)) +
        geom_boxplot(alpha = 0.3, outlier.shape = NA, show.legend = FALSE) +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        theme_minimal() +
        labs(title = i,
             subtitle = "Gene expression",
             x = "sv status",
             y = "FPKM-QN-NS")
      
      p2 <- ggplot(mat, aes(x=sv_status, y=fpkm.qn)) +
        geom_boxplot(alpha = 0.3, outlier.shape = NA, show.legend = FALSE) +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        scale_y_continuous(limits = c(0, NA)) +
        theme_minimal() +
        labs(title = i,
             subtitle = "Gene expression",
             x = "sv status",
             y = "FPKM-QN")
      
      p3 <- ggplot(mat, aes(x=sv_status, y=fpkm.qn.rle)) +
        geom_boxplot(alpha = 0.3, outlier.shape = NA, show.legend = FALSE) +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        theme_minimal() +
        labs(title = i,
             subtitle = "Gene expression",
             x = "sv status",
             y = "FPKM-QN-RLE")
      
      #pdf(paste0(opt$write, i, "_fpkm.qn.ns.pdf"), width = 4, height = 6)
      #print(p1)
      #dev.off()
      
      pdf(paste0(opt$write, i, "_fpkm.qn.pdf"), width = 4, height = 6)
      print(p2)
      dev.off()
      
      #pdf(paste0(opt$write, i, "_fpkm.qn.rle.pdf"), width = 4, height = 6)
      #print(p3)
      #dev.off()
      
      #if (median(mat[mat$sv_status == "no_sv"][,fpkm.qn]) == 0)
      #{
      #	FC <- c(FC, "Inf")
      #}
      #else
      #{
      #	FC <- c(FC, median(mat[mat$sv_status == "sv"][,fpkm.qn]) / median(mat[mat$sv_status == "no_sv"][,fpkm.qn]))
      #}
  		
  		mat$logexp = log10(mat$fpkm.qn+0.00000001)
  		mat <- subset(mat, select = - c(sample_id,fpkm.qn,fpkm.qn.ns,fpkm.qn.rle))
  		glm <- glm(logexp ~ ., data = as.data.frame(mat))
			summary <- summary(glm)
			FC <- c(FC, 10^summary$coefficients[rownames(summary$coefficients) == "sv_statussv", 1])
  		
  }

}

results <- cbind(results, FC)
write.table(results, file = paste0(opt$write, gsub(".txt", "", str_split(opt$results, "\\/")[[1]][length(str_split(opt$results, "\\/")[[1]])]), "_fc.txt"), quote = FALSE, sep = "\t", row.names = FALSE)


options(warn = oldw)