#!/bin/bash
oldw <- getOption("warn")
options(warn = -1)


suppressPackageStartupMessages(library(optparse))

option_list <- list(
  make_option(c("-e", "--exp"), action="store",
              help="Expression Rdata file generated by add_noise.R"),
  make_option(c("-w", "--write"), action="store", default="./intermediate/exp_pmt/",
              help="Folder for intermediate files [default %default]"),
  make_option(c("-x", "--prefix"), action="store", default="PMT",
              help="Prefix for output files [default %default]")
)

parser <- OptionParser(usage="%prog [options]", option_list=option_list, description="")
args <- parse_args(parser, positional_arguments=0)
opt <- args$options

load(opt$exp)

ids <- rownames(fpkm.qn.t)
ids_permuted <- sample(ids)
rownames(fpkm.qn.t) <- ids_permuted
rownames(fpkm.qn.t.ns) <- ids_permuted
rownames(pca.prcomp$x) <- ids_permuted

#write
if (file.exists(opt$write)) {
 save(fpkm.qn.t,fpkm.qn.t.ns,pca.prcomp, file = paste0(opt$write, opt$prefix, ".exp.Rdata"))
} else {
 dir.create(opt$write, recursive = TRUE)
 save(fpkm.qn.t,fpkm.qn.t.ns,pca.prcomp, file = paste0(opt$write, opt$prefix, ".exp.Rdata"))
}


options(warn = oldw)